// Generated by gencpp from file ui/robot_command.msg
// DO NOT EDIT!


#ifndef UI_MESSAGE_ROBOT_COMMAND_H
#define UI_MESSAGE_ROBOT_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ui
{
template <class ContainerAllocator>
struct robot_command_
{
  typedef robot_command_<ContainerAllocator> Type;

  robot_command_()
    : timeHeader()
    , CommandPosData()
    , CommandVelData()  {
    }
  robot_command_(const ContainerAllocator& _alloc)
    : timeHeader(_alloc)
    , CommandPosData(_alloc)
    , CommandVelData(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _timeHeader_type;
  _timeHeader_type timeHeader;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _CommandPosData_type;
  _CommandPosData_type CommandPosData;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _CommandVelData_type;
  _CommandVelData_type CommandVelData;





  typedef boost::shared_ptr< ::ui::robot_command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ui::robot_command_<ContainerAllocator> const> ConstPtr;

}; // struct robot_command_

typedef ::ui::robot_command_<std::allocator<void> > robot_command;

typedef boost::shared_ptr< ::ui::robot_command > robot_commandPtr;
typedef boost::shared_ptr< ::ui::robot_command const> robot_commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ui::robot_command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ui::robot_command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ui

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ui': ['/home/ch/code/birl_climbot_location/src/BirlModuleRobot/ui/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ui::robot_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ui::robot_command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ui::robot_command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ui::robot_command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ui::robot_command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ui::robot_command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ui::robot_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc01d01e3e5b26ff37d3ece2d39ae6d6";
  }

  static const char* value(const ::ui::robot_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc01d01e3e5b26ffULL;
  static const uint64_t static_value2 = 0x37d3ece2d39ae6d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::ui::robot_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ui/robot_command";
  }

  static const char* value(const ::ui::robot_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ui::robot_command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 时间戳\n\
Header timeHeader\n\
# 关节位置命令 I1 T2 T3 T4 I5\n\
float32[] CommandPosData\n\
# 关节速度命令\n\
float32[] CommandVelData\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::ui::robot_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ui::robot_command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timeHeader);
      stream.next(m.CommandPosData);
      stream.next(m.CommandVelData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ui::robot_command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ui::robot_command_<ContainerAllocator>& v)
  {
    s << indent << "timeHeader: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.timeHeader);
    s << indent << "CommandPosData[]" << std::endl;
    for (size_t i = 0; i < v.CommandPosData.size(); ++i)
    {
      s << indent << "  CommandPosData[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.CommandPosData[i]);
    }
    s << indent << "CommandVelData[]" << std::endl;
    for (size_t i = 0; i < v.CommandVelData.size(); ++i)
    {
      s << indent << "  CommandVelData[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.CommandVelData[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UI_MESSAGE_ROBOT_COMMAND_H
