// Generated by gencpp from file birl_module_robot/inverse_solutionResponse.msg
// DO NOT EDIT!


#ifndef BIRL_MODULE_ROBOT_MESSAGE_INVERSE_SOLUTIONRESPONSE_H
#define BIRL_MODULE_ROBOT_MESSAGE_INVERSE_SOLUTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace birl_module_robot
{
template <class ContainerAllocator>
struct inverse_solutionResponse_
{
  typedef inverse_solutionResponse_<ContainerAllocator> Type;

  inverse_solutionResponse_()
    : joint_pos_commands()
    , joint_vel_commands()  {
    }
  inverse_solutionResponse_(const ContainerAllocator& _alloc)
    : joint_pos_commands(_alloc)
    , joint_vel_commands(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _joint_pos_commands_type;
  _joint_pos_commands_type joint_pos_commands;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _joint_vel_commands_type;
  _joint_vel_commands_type joint_vel_commands;





  typedef boost::shared_ptr< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct inverse_solutionResponse_

typedef ::birl_module_robot::inverse_solutionResponse_<std::allocator<void> > inverse_solutionResponse;

typedef boost::shared_ptr< ::birl_module_robot::inverse_solutionResponse > inverse_solutionResponsePtr;
typedef boost::shared_ptr< ::birl_module_robot::inverse_solutionResponse const> inverse_solutionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace birl_module_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f62639cfbedb0e764507d1d70b9c0bf";
  }

  static const char* value(const ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f62639cfbedb0e7ULL;
  static const uint64_t static_value2 = 0x64507d1d70b9c0bfULL;
};

template<class ContainerAllocator>
struct DataType< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "birl_module_robot/inverse_solutionResponse";
  }

  static const char* value(const ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
float32[] joint_pos_commands\n\
\n\
\n\
\n\
float32[] joint_vel_commands\n\
\n\
";
  }

  static const char* value(const ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_pos_commands);
      stream.next(m.joint_vel_commands);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct inverse_solutionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::birl_module_robot::inverse_solutionResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint_pos_commands[]" << std::endl;
    for (size_t i = 0; i < v.joint_pos_commands.size(); ++i)
    {
      s << indent << "  joint_pos_commands[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_pos_commands[i]);
    }
    s << indent << "joint_vel_commands[]" << std::endl;
    for (size_t i = 0; i < v.joint_vel_commands.size(); ++i)
    {
      s << indent << "  joint_vel_commands[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_vel_commands[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIRL_MODULE_ROBOT_MESSAGE_INVERSE_SOLUTIONRESPONSE_H
