// Generated by gencpp from file birl_module_robot/inverse_solution.msg
// DO NOT EDIT!


#ifndef BIRL_MODULE_ROBOT_MESSAGE_INVERSE_SOLUTION_H
#define BIRL_MODULE_ROBOT_MESSAGE_INVERSE_SOLUTION_H

#include <ros/service_traits.h>


#include <birl_module_robot/inverse_solutionRequest.h>
#include <birl_module_robot/inverse_solutionResponse.h>


namespace birl_module_robot
{

struct inverse_solution
{

typedef inverse_solutionRequest Request;
typedef inverse_solutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct inverse_solution
} // namespace birl_module_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::birl_module_robot::inverse_solution > {
  static const char* value()
  {
    return "fd70c212af5c1d03d9d1a73214023d9c";
  }

  static const char* value(const ::birl_module_robot::inverse_solution&) { return value(); }
};

template<>
struct DataType< ::birl_module_robot::inverse_solution > {
  static const char* value()
  {
    return "birl_module_robot/inverse_solution";
  }

  static const char* value(const ::birl_module_robot::inverse_solution&) { return value(); }
};


// service_traits::MD5Sum< ::birl_module_robot::inverse_solutionRequest> should match 
// service_traits::MD5Sum< ::birl_module_robot::inverse_solution > 
template<>
struct MD5Sum< ::birl_module_robot::inverse_solutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::birl_module_robot::inverse_solution >::value();
  }
  static const char* value(const ::birl_module_robot::inverse_solutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::birl_module_robot::inverse_solutionRequest> should match 
// service_traits::DataType< ::birl_module_robot::inverse_solution > 
template<>
struct DataType< ::birl_module_robot::inverse_solutionRequest>
{
  static const char* value()
  {
    return DataType< ::birl_module_robot::inverse_solution >::value();
  }
  static const char* value(const ::birl_module_robot::inverse_solutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::birl_module_robot::inverse_solutionResponse> should match 
// service_traits::MD5Sum< ::birl_module_robot::inverse_solution > 
template<>
struct MD5Sum< ::birl_module_robot::inverse_solutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::birl_module_robot::inverse_solution >::value();
  }
  static const char* value(const ::birl_module_robot::inverse_solutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::birl_module_robot::inverse_solutionResponse> should match 
// service_traits::DataType< ::birl_module_robot::inverse_solution > 
template<>
struct DataType< ::birl_module_robot::inverse_solutionResponse>
{
  static const char* value()
  {
    return DataType< ::birl_module_robot::inverse_solution >::value();
  }
  static const char* value(const ::birl_module_robot::inverse_solutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BIRL_MODULE_ROBOT_MESSAGE_INVERSE_SOLUTION_H
